Pystagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index
from users.views import profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('posts/', include("posts.urls")),
    path("", index),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

Pystagram/posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name = "feeds"),
    path("comment_add/", comment_add, name = "comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>", post_like, name = "post_like"),
]

Pystagram/users/urls.py
from django.urls import path, include
from users.views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name = "follow")
]

Pystagram/posts/models.py
from django.db import models
from django.contrib.admin.widgets import AdminFileWidget
from django.utils.safestring import mark_safe


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

    tags = models.ManyToManyField("posts.HashTag", verbose_name = "list of HashTag", blank = True)

    def __str__(self):
        return f"{self.user.username}'s Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    photo = models.ImageField(
        "Photo", upload_to = "post"
    )

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

class HashTag(models.Model):
    name = models.CharField("Tag_name", max_length = 50)

    def __str__(self):
        return self.name

Pystagram/templates/_base.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Pystagram</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}
</body>
</html>

Pystagram/templates/base.html
{% extends '_base.html' %}

{% block base_content %}
    {% block content %}{% endblock %}
{% endblock %}

Pystagram/templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

Pystagram/templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>
                        <a href="{% url 'users:profile' user_id=user.id %}">
                            {{ user.post_set.count }}</a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'users:followers' user_id=user.id %}">
                            {{ user.followers.count }}</a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'users:following' user_id=user.id %}">
                           {{ user.following.count }}</a>
                    </dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
        </div>
    </div>
    {% block bottom_data %}{% endblock %}
</div>

{% endblock %}

Pystagram/templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

Pystagram/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div>Home Page</div>
</body>
</html>

Pystagram/templates/nav.html
    <nav>
        <h1>
            <a href="{% url 'posts:feeds' %}">Pystagram</a>
        </h1>
        <a href="{% url 'posts:post_add' %}">Add post</a>
        <a href="{% url 'users:logout' %}">Logout</a>

    </nav>