Pystagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index
from users.views import profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('posts/', include("posts.urls")),
    path("", index),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

Pystagram/posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name = "feeds"),
    path("comment_add/", comment_add, name = "comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>", post_like, name = "post_like"),
]

Pystagram/users/urls.py
from django.urls import path, include
from users.views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name = "follow")
]

Pystagram/posts/models.py
from django.db import models
from django.contrib.admin.widgets import AdminFileWidget
from django.utils.safestring import mark_safe


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

    tags = models.ManyToManyField("posts.HashTag", verbose_name = "list of HashTag", blank = True)

    def __str__(self):
        return f"{self.user.username}'s Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    photo = models.ImageField(
        "Photo", upload_to = "post"
    )

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

class HashTag(models.Model):
    name = models.CharField("Tag_name", max_length = 50)

    def __str__(self):
        return self.name

Pystagram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class User(AbstractUser):
    profile_image = models.ImageField(
        "profile_image", upload_to = "users/profile", blank = True
    )
    short_description = models.TextField("description", blank = True)

    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name = "Liked Posts",
        related_name = "like_users",
        blank = True,
    )
    following = models.ManyToManyField(
        "self",
        verbose_name = "People i follow",
        related_name = "followers",
        symmetrical = False,
        through = "users.Relationship",
    )

    def __str__(self):
        return self.username

class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name = "User who sent a follow request",
        related_name = "following_relationships",
        on_delete = models.CASCADE,
    )

    to_user = models.ForeignKey(
        "users.User",
        verbose_name = "User who requested to follow",
        related_name = "follower_relationships",
        on_delete = models.CASCADE,
    )

    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"relationship ({self.from_user}) -> ({self.to_user})"

Pystagram/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        min_length = 3,
        widget = forms.TextInput(
            attrs = {"placeholder" : "username (min 3letters)"},
        ),
    )
    password = forms.CharField(
        min_length = 4,
        widget = forms.TextInput(
            attrs = {"placeholder" : "password (at least 4 letters)"},
        ),
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username = username).exists():
            raise ValidationError(f"{username} is already exists")
        return username

    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            self.add_error("password2", "passwords do not match")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]

        user = User.objects.create_user(
            username = username,
            password = password1,
            profile_image = profile_image,
            short_description = short_description,
        )

        return user

Pystagram/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import LoginForm, SignupForm
from users.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def login_view(request):
    if request.user.is_authenticated:
        return redirect("posts:feeds")

    if request.method == "POST":
        form = LoginForm(data = request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(username = username, password = password)

            if user:
                login(request, user)
                return redirect("posts:feeds")

            else:
                # print("login failed")
                form.add_error(None, "There is no user for this data")
        context = {"form": form}
        return render(request, "users/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form}
        return render(request, "users/login.html", context)

def logout_view(request):
    logout(request)

    return redirect("users:login")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data = request.POST, files = request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("posts:feeds")

    else:
        form = SignupForm()
    context = {
        "form" : form
    }
    return render(request, "users/signup.html", context)

def profile(request, user_id):
    user = get_object_or_404(User, id = user_id)
    context = {
        "user" : user,
    }
    return render(request, "users/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id = user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user" : user,
        "relationships" : relationships,
    }
    return render(request, "users/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id = user_id)
    relationships = user.following_relationships.all()
    context = {
        "user" : user,
        "relationship" : relationships,
    }
    return render(request, "users/following.html", context)

def follow(request, user_id):
    user = request.user

    target_user = get_object_or_404(User, id = user_id)

    if target_user in user.following.all():
        # 팔로잉 목록에서 제거
            user.following.remove(target_user)
    else:
        user.following.add(target_user)

    url_next = request.GET.get("next") or reverse("users:profile", args = [user.id])
    return HttpResponseRedirect(url_next)

Pystagram/templates/users/followers.html
{% extends 'base_profile.html' %}

{% block bottom_data %}

<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                {% if relationship.from_user.profile_image %}
                    <img src="{{ relationship.from_user.profile_image.url }}">
                {% endif %}
                <div class="relationship.info">
                    <span>{{ relationship.from_user.username }}</span>
                    <span>{{ relationship.created|date:"y.m.d" }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

Pystagram/templates/users/following.html
{% extends 'base_profile.html' %}

{% block bottom_data %}

<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                {% if relationship.from_user.profile_image %}
                    <img src="{{ relationship.from_user.profile_image.url }}">
                {% endif %}
                <div class="relationship.info">
                    <span>{{ relationship.from_user.username }}</span>
                    <span>{{ relationship.created|date:"y.m.d" }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

Pystagram/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<div id="login">
    <form method="POST" enctype="multipart/form-data">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-login">Login</button>
        <a href="{% url 'users:signup' %}">move to signup</a>
    </form>
</div>

{% endblock %}

Pystagram/templates/users/profile.html
{% extends 'base_profile.html' %}

{% block bottom_data %}

<div class="post-grid-container">
    {% for post in user.post_set.all %}
        {% if post.postimage_set.first and post.postimage_set.first.photo %}
            <div class="post-grid">
                <a href="{% url 'posts:post_detail' post_id=post.id %}">
                    <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                </a>
            </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}

Pystagram/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}

<div id="signup">
    <form method="POST" enctype="multipart/form-data">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">signup</button>
        <a href="{% url 'users:login' %}">move to login page</a>
    </form>
</div>

{% endblock %}