Pystagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index
from users.views import profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('posts/', include("posts.urls")),
    path("", index),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

Pystagram/posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name = "feeds"),
    path("comment_add/", comment_add, name = "comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name = "comment_delete"),
    path("post_add/", post_add, name = "post_add"),
    path("tags/<str:tag_name>/", tags, name = "tags"),
    path("<int:post_id>/", post_detail, name = "post_detail"),
    path("<int:post_id>", post_like, name = "post_like"),
]

Pystagram/users/urls.py
from django.urls import path, include
from users.views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name = "login"),
    path("logout/", logout_view, name = "logout"),
    path("signup/", signup, name = "signup"),
    path("<int:user_id>/profile/", profile, name = "profile"),
    path("<int:user_id>/followers/", followers, name = "followers"),
    path("<int:user_id>/following/", following, name = "following"),
    path("<int:user_id>/follow/", follow, name = "follow")
]

Pystagram/posts/models.py
from django.db import models
from django.contrib.admin.widgets import AdminFileWidget
from django.utils.safestring import mark_safe


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

    tags = models.ManyToManyField("posts.HashTag", verbose_name = "list of HashTag", blank = True)

    def __str__(self):
        return f"{self.user.username}'s Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    photo = models.ImageField(
        "Photo", upload_to = "post"
    )

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name = "Author",
        on_delete = models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name = "post",
        on_delete = models.CASCADE,
    )
    content = models.TextField("content")
    created = models.DateField("Created on", auto_now_add = True)

class HashTag(models.Model):
    name = models.CharField("Tag_name", max_length = 50)

    def __str__(self):
        return self.name

Pystagram/posts/forms.py
from django import forms
from posts.models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content" : forms.Textarea(
                attrs={
                    "placeholder" : "leave a comment",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

Pystagram/posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, Comment, PostImage, HashTag
from posts.forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

# Create your views here.

def feeds(request):

    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts" : posts,
        "comment_form" : comment_form,
    }
    return render(request, "posts/feeds.html", context)

@require_POST

def comment_add(request):
    print(require_POST)

    form = CommentForm(data = request.POST)
    print(request.user)
    print(form.is_valid())

    if form.is_valid():
        # commit = False option을 이용해서 메모리상에 Commit 객체 생성
        comment = form.save(commit = False)

        comment.user = request.user

        comment.save()

        print(comment.id)
        print(comment.content)
        print(comment.user)
        if request.GET.get("next"):
            url_next = request.GET.get('next')
        else:
            url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"

        return HttpResponseRedirect(url_next)

@require_POST
def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("you don't have permission to delete tins comment")

def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content"는 PostForm으로 처리
        form = PostForm(data = request.POST)

        if form.is_valid():
            # Post의 "user" 값은 request에거 가져와 자동 할당한다.
            post = form.save(commit = False)
            post.user = request.user
            post.save()

            for image_file in request.FILES.getlist("images"):
                # request.FILES 또는 request.FILES.getlist()로 가져온 파일들은
                # Model의 ImageField 부분에 곧바로 할당된다.
                PostImage.objects.create(
                    post = post,
                    photo = image_file,
                )
            # Post의 생성이 완료되면, 생성된 Post의 위치로 이동하도록 한다.
            tag_string = request.POST.get("tags")
            tag_list = [i.strip() for i in tag_string.split(",")]
            print(tag_list)
            for tag_name in tag_list:
                tag, _= HashTag.objects.get_or_create(name = tag_name)
                print(tag)
                post.tags.add(tag)
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)
    else:
        form = PostForm()

        context = {
            "form" : form
        }

        return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name = tag_name)
    except HashTag.DoesNotExist:
        #tag_name에 해당하는 HashTag를 찾지 못한 경우, 빈 Query를 돌려준다.
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags = tag)

    context = {
        "tag_name" : tag_name,
        "posts" : posts,
    }
    return render(request, "posts/tags.html", context)

def post_detail(request, post_id):
    post = Post.objects.get(id = post_id)
    comment_form = CommentForm()
    context = {
        "post" : post,
        "comment_form" : comment_form,
    }

    return render(request, "posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id = post_id)
    user = request.user

    if user.like_posts.filter(id = post.id).exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"

    return HttpResponseRedirect(url_next)

Pystagram/templates/posts/feeds.html
{% extends 'base_slider.html' %}
{% load custom_tags %}

{% block content %}
    <div id="feeds" class="post-container">
        {% for post in posts %}
            {% with post.id|stringformat:"s" as post_id %}
                {% url 'posts:feeds' as action_redirect_to %}
                {% include 'posts/post.html' with action_redirect_url=action_redirect_to|add:'#post-'|add:post_id %}
            {% endwith %}
        {% endfor %}
    </div>
{% endblock %}

Pystagram/templates/posts/post.html
    <article id="post-{{ post.id }}" class="post">
        <header class="post-header">
            <a href="{% url 'users:profile' user_id=post.user.id %}">
                {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}">
                {% endif %}
                <span>{{ post.user.username }}</span>
            </a>

            {% if user != post.user %}
                <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn=primary">
                        {% if post.user in user.following.all %}
                            Unfollow
                        {% else %}
                            Follow
                        {% endif %}
                    </button>
                </form>
            {% endif %}
        </header>
        <div class="post-images splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for image in post.postimage_set.all %}
                    {% if image.photo %}
                    <li class="splide__slide">
                        <img src="{{ image.photo.url }}">
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="post-content">
            {{ post.content | linebreaksbr }}
            <div class="post-tags">
                {% for tag in post.tags.all %}
                <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="post-buttons">
            <form action="{% url 'posts:post_like' post_id=post.id %}?next={{ action_redirect_url }}" method="POST">
                {% csrf_token %}
                <button
                    type="submit"
                    {% if user in post.like_users.all %}
                        style="color: red ;"
                    {% endif %}>
                        Likes({{ post.like_users.count }})
                </button>

            </form>
            <span>Comments({{ post.comment_set.count }})</span>
        </div>
        <div class="post-comments">
            <ul>
                {% for comment in post.comment_set.all %}
                <li>
                    <span>{{ comment.user.username }}</span>
                    <span>{{ comment.content }}</span>
                    {% if user == comment.user %}
                    <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
<!--                              <form method="POST" action="/posts/comment_delete/{{ comment.id }}/"> 기존방식    -->
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                    {% endif %}
                </li>{% endfor %}
            </ul>
        </div>
        <small>{{ post.created }}</small>
        <div class="post-comment-create">
            <form method="POST"
                  action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.id }}">
                {{ comment_form.content }}
                <button type="submit">Enter</button>
            </form>
        </div>
    </article>

Pystagram/templates/posts/post_add.html
{% extends 'base.html' %}

{% block content %}
    <nav>
        <h1><a href="/posts/feeds/">Pystagram</a></h1>
        <a href="/users/logout/">Logout</a>
    </nav>
    <div id="post-add">
        <h1>Add Post</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_images">Image</label>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <div>
                <label for="id_tags">HashTag</label>
                <input id="id_tags" name="tags"
                       type="text" placeholder="Separate tags with commas.">
            </div>
            <button type="submit">Publish Post</button>
        </form>
    </div>
{% endblock %}

Pystagram/templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}

{% include 'nav.html' %}
    <div id="feeds" class="post-container">
        {% url 'posts:post_detail' post.id as action_redirect_to %}
        {% include 'posts/post.html' %}
    </div>

{% endblock %}

Pystagram/templates/posts/tags.html
{% extends 'base_nav.html' %}

{% block content %}

<div id="tags">
    <header class = "tags-header">
        <h2>#{{ tag_name }}</h2>
        <div>Posts({{ posts.count }})</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}

<!--            Post에 연결된 PostImage가 있으며, 연결된 첫 번째 Post Imange의 photo가 있는경우-->
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <a href="{% url 'posts:post_detail' post_id = post.id %}">
                        <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                    </a>
                </div>
            {% endif %}
        {% empty %}
                <p>No search results found.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}